version: '3.1'
services:

  db1:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'

  db2:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DATABASE: app
      POSTGRES_USER: app
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  node:
    image: node:8
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./data/node/gate-simulator:/home/node/app
    ports:
      - '9999:9999'
    command: "npm start"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - db1
    environment:
      - PMA_ARBITRARY=1

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
    - "5050:80"
    volumes:
    - ./data/pgadmin-data:/var/lib/pgadmin